### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by ArtInLines** [DHBW-Vilas/21ai1-webeng-II-webitor#20]
We should take a look at our app from a usability standpoint and see whether anything should change. For example, we mght decide that showing he Sign Up button is confusing when the user is already logged in

**Comment by JakobPK** [comment]
About usability and smaller issues:

- [ ] login buttton ausgrauen wenn eingeloggt
- [ ] logout button?
- [ ] Benennung von Workspaces - brauchen eine message das workspaces nicht geöffnet werden wenn # im Namen vorkommt
- [ ] Funktioniert save inzwischen? Der Button macht bisher nichts vernünftiges. We could also take it out if its not needed

**Comment by ArtInLines** [comment]
Statt Login button auszugrauen, wenn der User schon eingeloggt ist, können wir den Login button doch auch einfach rausnehmen. Zum Beispiel einfach über javascript `loginButton.style.display = "none"` oder so in der Art.

**Comment by ArtInLines** [comment]
Save funktioniert eigentlich, kann aber sein, dass ich vergessen hatte den button auch einzubinden, schaue ich mir nachher nochmal an
