### ISSUE TITLE
Editor Layout

### ISSUE THREAD

**Issue by JakobPK** [DHBW-Vilas/21ai1-webeng-II-webitor#5]
1. different styles like in home
2. header 

- [ ] show user
- [ ] change arrangment of style change buttons
- [ ] go back to home
- [x] save work

**Comment by ArtInLines** [comment]
With `save work` you mean downloading the workspace from the server?

**Comment by JakobPK** [comment]
Yes, if we want to include that function? If I remember correctly we wanted to either save the workspace on our server or let users download their work. Right?

**Comment by ArtInLines** [comment]
Yes exactly.

**Comment by ArtInLines** [comment]
Extracted into separate issues
