### ISSUE TITLE
Editor - Codemirror extensions

### ISSUE THREAD

**Issue by JakobPK** [DHBW-Vilas/21ai1-webeng-II-webitor#7]
- [x] Highlighting
- [x] Code Completion?
- [x] code folding?
- [x] close brackets?
- [x] history?
- [x] search?

**Comment by ArtInLines** [comment]
How I would implement the Hello World for new workspaces:

- StartPage offers button to create new workspace of chosen language
- The button sends a POST-request to `/create/:workspaceName/:language`
- The server creates the new workspace including the necessary files for the hello world in the provided language
- The server responds with the ID of the newly created workspace
- Client stores the ID in localStorage and redirects itself to `/editor`

**Comment by ArtInLines** [comment]
resolved in 04e9505
